export const PERMISSION_GROUPS = [
  {
    id: "19637fbb73d242c0a92845d8db0b95b1",
    name: "aiaudit",
    description: "Grants access to reading AI Audit",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "aiaudit_read",
    type: "read",
    rowId: 1138,
    parsedName: "AI Audit",
  },
  {
    id: "1ba6ab4cacdb454b913bbb93e1b8cb8c",
    name: "aiaudit",
    description: "Grants access to reading and editing AI Audit",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "aiaudit_write",
    type: "edit",
    rowId: 1139,
    parsedName: "AI Audit",
  },
  {
    id: "4dc8917b4b40457d88d3035d5dadb054",
    name: "aig",
    description: "Grants access to reading AI Gateways",
    scopes: ["com.cloudflare.api.account"],
    label: "aig_read",
    type: "read",
    rowId: 1140,
    parsedName: "AI Gateway",
  },
  {
    id: "644535f4ed854494a59cb289d634b257",
    name: "aig",
    description: "Grants access to run AI Gateways",
    scopes: ["com.cloudflare.api.account"],
    label: "aig_run",
    type: "run",
    rowId: 1141,
    parsedName: "AI Gateway",
  },
  {
    id: "6c8a3737f07f46369c1ea1f22138daaf",
    name: "aig",
    description: "Grants access to reading and editing AI Gateways",
    scopes: ["com.cloudflare.api.account"],
    label: "aig_write",
    type: "edit",
    rowId: 1142,
    parsedName: "AI Gateway",
  },
  {
    id: "0cc3a61731504c89b99ec1be78b77aa0",
    name: "api_tokens",
    description: "Grants read access to user's API Tokens",
    scopes: ["com.cloudflare.api.user"],
    label: "api_tokens_read",
    type: "read",
    rowId: 1143,
    parsedName: "API Tokens",
  },
  {
    id: "686d18d5ac6c441c867cbf6771e58a0a",
    name: "api_tokens",
    description: "Grants write access to user's API Tokens",
    scopes: ["com.cloudflare.api.user"],
    label: "api_tokens_write",
    type: "edit",
    rowId: 1144,
    parsedName: "API Tokens",
  },
  {
    id: "eb258a38ea634c86a0c89da6b27cb6b6",
    name: "zone_access",
    description: "Grants read access to Cloudflare Access zone resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_access_read",
    type: "read",
    rowId: 1145,
    parsedName: "Access: Apps and Policies",
  },
  {
    id: "7ea222f6d5064cfa89ea366d7c1fee89",
    name: "access",
    description: "Grants read access to Cloudflare Access account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "access_read",
    type: "read",
    rowId: 1146,
    parsedName: "Access: Apps and Policies",
  },
  {
    id: "6db4e222e21248ac96a3f4c2a81e3b41",
    name: "zone_access",
    description:
      "Grants ability to revoke all tokens to Cloudflare Access zone resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_access_revoke",
    type: "revoke",
    rowId: 1147,
    parsedName: "Access: Apps and Policies",
  },
  {
    id: "6c9d1cfcfc6840a987d1b5bfb880a841",
    name: "access",
    description:
      "Grants ability to revoke all tokens to Cloudflare Access account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "access_revoke",
    type: "revoke",
    rowId: 1148,
    parsedName: "Access: Apps and Policies",
  },
  {
    id: "959972745952452f8be2452be8cbb9f2",
    name: "zone_access",
    description: "Grants write access to Cloudflare Access zone resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_access_write",
    type: "edit",
    rowId: 1149,
    parsedName: "Access: Apps and Policies",
  },
  {
    id: "1e13c5124ca64b72b1969a67e8829049",
    name: "access",
    description: "Grants write access to Cloudflare Access account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "access_write",
    type: "edit",
    rowId: 1150,
    parsedName: "Access: Apps and Policies",
  },
  {
    id: "b05b28e839c54467a7d6cba5d3abb5a3",
    name: "access_audit_log",
    description: "Grants read access to Cloudflare Access audit logs",
    scopes: ["com.cloudflare.api.account"],
    label: "access_audit_log_read",
    type: "read",
    rowId: 1151,
    parsedName: "Access: Audit Logs",
  },
  {
    id: "4f3196a5c95747b6ad82e34e1d0a694f",
    name: "access_certificate",
    description: "Grants read access to Cloudflare Access MTLS certificates",
    scopes: ["com.cloudflare.api.account"],
    label: "access_certificate_read",
    type: "read",
    rowId: 1152,
    parsedName: "Access: Mutual TLS Certificates",
  },
  {
    id: "29d3afbfd4054af9accdd1118815ed05",
    name: "access_certificate",
    description: "Grants write access to Cloudflare Access MTLS certificates",
    scopes: ["com.cloudflare.api.account"],
    label: "access_certificate_write",
    type: "edit",
    rowId: 1153,
    parsedName: "Access: Mutual TLS Certificates",
  },
  {
    id: "08e61dabe81a422dab0dea6fdef1a98a",
    name: "access_custom_page",
    description: "Grants read access to Cloudflare Access Custom Pages",
    scopes: ["com.cloudflare.api.account"],
    label: "access_custom_page_read",
    type: "read",
    rowId: 1154,
    parsedName: "Access: Custom Pages",
  },
  {
    id: "4e5fd8ac327b4a358e48c66fcbeb856d",
    name: "access_custom_page",
    description: "Grants write access to Cloudflare Access Custom Pages",
    scopes: ["com.cloudflare.api.account"],
    label: "access_custom_page_write",
    type: "edit",
    rowId: 1155,
    parsedName: "Access: Custom Pages",
  },
  {
    id: "0f4841f80adb4bada5a09493300e7f8d",
    name: "access_device_posture",
    description: "Grants read access to Cloudflare Access Device Posture",
    scopes: ["com.cloudflare.api.account"],
    label: "access_device_posture_read",
    type: "read",
    rowId: 1156,
    parsedName: "Access: Device Posture",
  },
  {
    id: "2fc1072ee6b743828db668fcb3f9dee7",
    name: "access_device_posture",
    description: "Grants write access to Cloudflare Access Device Posture",
    scopes: ["com.cloudflare.api.account"],
    label: "access_device_posture_write",
    type: "edit",
    rowId: 1157,
    parsedName: "Access: Device Posture",
  },
  {
    id: "26bc23f853634eb4bff59983b9064fde",
    name: "access_acct",
    description: "Grants read access to Cloudflare Access account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "access_acct_read",
    type: "read",
    rowId: 1158,
    parsedName: "Access: Organizations, Identity Providers, and Groups",
  },
  {
    id: "7121a0c7e9ed46e3829f9cca2bb572aa",
    name: "access_acct",
    description:
      "Grants ability to revoke user sessions to Cloudflare Access account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "access_acct_revoke",
    type: "revoke",
    rowId: 1159,
    parsedName: "Access: Organizations, Identity Providers, and Groups",
  },
  {
    id: "bfe0d8686a584fa680f4c53b5eb0de6d",
    name: "access_acct",
    description: "Grants write access to Cloudflare Access account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "access_acct_write",
    type: "edit",
    rowId: 1160,
    parsedName: "Access: Organizations, Identity Providers, and Groups",
  },
  {
    id: "de99c87e48d642ce8c985d027905b475",
    name: "access_population",
    description: "Grants read access to Cloudflare Access Populations",
    scopes: ["com.cloudflare.api.account"],
    label: "access_population_read",
    type: "read",
    rowId: 1161,
    parsedName: "Access: Populations",
  },
  {
    id: "bc783549a3a741aaa10556faf8b485bb",
    name: "access_population",
    description: "Grants write access to Cloudflare Access Populations",
    scopes: ["com.cloudflare.api.account"],
    label: "access_population_write",
    type: "edit",
    rowId: 1162,
    parsedName: "Access: Populations",
  },
  {
    id: "99ff99e4e30247a99d3777a8c4c18541",
    name: "access_ssh_auditing",
    description:
      "Grants read access to Cloudflare Access SSH Auditing Certificate Authorities",
    scopes: ["com.cloudflare.api.account"],
    label: "access_ssh_auditing_read",
    type: "read",
    rowId: 1163,
    parsedName: "Access: SSH Auditing",
  },
  {
    id: "d30c9ad8b5224e7cb8d41bcb4757effc",
    name: "access_ssh_auditing",
    description:
      "Grants write access to Cloudflare Access SSH Auditing Certificate Authorities",
    scopes: ["com.cloudflare.api.account"],
    label: "access_ssh_auditing_write",
    type: "edit",
    rowId: 1164,
    parsedName: "Access: SSH Auditing",
  },
  {
    id: "91f7ce32fa614d73b7e1fc8f0e78582b",
    name: "access_service_token",
    description: "Grants read access to Cloudflare Access Service Tokens",
    scopes: ["com.cloudflare.api.account"],
    label: "access_service_token_read",
    type: "read",
    rowId: 1165,
    parsedName: "Access: Service Tokens",
  },
  {
    id: "a1c0fec57cf94af79479a6d827fa518c",
    name: "access_service_token",
    description: "Grants write access to Cloudflare Access Service Tokens",
    scopes: ["com.cloudflare.api.account"],
    label: "access_service_token_write",
    type: "edit",
    rowId: 1166,
    parsedName: "Access: Service Tokens",
  },
  {
    id: "5e5d3e8efeec49f3afb67bafecbcd511",
    name: "account_api_gateway",
    description:
      "Grants full access to API-Gateway Management (including API Shield) across the whole account",
    scopes: ["com.cloudflare.api.account"],
    label: "account_api_gateway_write",
    type: "edit",
    rowId: 1167,
    parsedName: "API Gateway",
  },
  {
    id: "05a2a65760a546439ed29762b163cece",
    name: "account_api_gateway",
    description:
      "Grants read access to API-Gateway Management (including API Shield) across the whole account",
    scopes: ["com.cloudflare.api.account"],
    label: "account_api_gateway_read",
    type: "read",
    rowId: 1168,
    parsedName: "API Gateway",
  },
  {
    id: "eb56a6953c034b9d97dd838155666f06",
    name: "account_api_tokens",
    description: "Grants read access to account API Tokens",
    scopes: ["com.cloudflare.api.account"],
    label: "account_api_tokens_read",
    type: "read",
    rowId: 1169,
    parsedName: "API Tokens",
  },
  {
    id: "5bc3f8b21c554832afc660159ab75fa4",
    name: "account_api_tokens",
    description: "Grants write access to account API Tokens",
    scopes: ["com.cloudflare.api.account"],
    label: "account_api_tokens_write",
    type: "edit",
    rowId: 1170,
    parsedName: "API Tokens",
  },
  {
    id: "b89a480218d04ceb98b4fe57ca29dc1f",
    name: "account_analytics",
    description: "Grants read access to analytics",
    scopes: ["com.cloudflare.api.account"],
    label: "account_analytics_read",
    type: "read",
    rowId: 1171,
    parsedName: "Account Analytics",
  },
  {
    id: "c57ea647ef654b47bc8944fa739b570d",
    name: "account_custom_pages",
    description: "Grants read access to account custom pages",
    scopes: ["com.cloudflare.api.account"],
    label: "account_custom_pages_read",
    type: "read",
    rowId: 1172,
    parsedName: "Account Custom Pages",
  },
  {
    id: "8a9d35a7c8504208ad5c3e8d58e6162d",
    name: "account_custom_pages",
    description: "Grants write access to account custom pages",
    scopes: ["com.cloudflare.api.account"],
    label: "account_custom_pages_write",
    type: "edit",
    rowId: 1173,
    parsedName: "Account Custom Pages",
  },
  {
    id: "cfa964bcdafc4ab39704e7476154e41b",
    name: "account_dns_settings",
    description: "Grants read access to Account DNS Settings",
    scopes: ["com.cloudflare.api.account"],
    label: "account_dns_settings_read",
    type: "read",
    rowId: 1174,
    parsedName: "Account DNS Settings",
  },
  {
    id: "dc44f27f48ab405392a5f69fe822bd01",
    name: "account_dns_settings",
    description: "Grants write access to Account DNS Settings",
    scopes: ["com.cloudflare.api.account"],
    label: "account_dns_settings_write",
    type: "edit",
    rowId: 1175,
    parsedName: "Account DNS Settings",
  },
  {
    id: "de7a688cc47d43bd9ea700b467a09c96",
    name: "account_firewall_access_rules",
    description: "Grants read access to account firewall access rules",
    scopes: ["com.cloudflare.api.account"],
    label: "account_firewall_access_rules_read",
    type: "read",
    rowId: 1176,
    parsedName: "Account Firewall Access Rules",
  },
  {
    id: "a416acf9ef5a4af19fb11ed3b96b1fe6",
    name: "account_firewall_access_rules",
    description: "Grants write access to account firewall access rules",
    scopes: ["com.cloudflare.api.account"],
    label: "account_firewall_access_rules_write",
    type: "edit",
    rowId: 1177,
    parsedName: "Account Firewall Access Rules",
  },
  {
    id: "4f1071168de8466e9808de86febfc516",
    name: "account_rule_lists",
    description: "Grants read access to Rule Lists",
    scopes: ["com.cloudflare.api.account"],
    label: "account_rule_lists_read",
    type: "read",
    rowId: 1178,
    parsedName: "Account Filter Lists",
  },
  {
    id: "2edbf20661fd4661b0fe10e9e12f485c",
    name: "account_rule_lists",
    description: "Grants write access to Rule Lists",
    scopes: ["com.cloudflare.api.account"],
    label: "account_rule_lists_write",
    type: "edit",
    rowId: 1179,
    parsedName: "Account Filter Lists",
  },
  {
    id: "fb39996ee9044d2a8725921e02744b39",
    name: "account_rulesets",
    description: "Grants read access to Account Rulesets",
    scopes: ["com.cloudflare.api.account"],
    label: "account_rulesets_read",
    type: "read",
    rowId: 1180,
    parsedName: "Account Rulesets",
  },
  {
    id: "56907406c3d548ed902070ec4df0e328",
    name: "account_rulesets",
    description: "Grants write access to Account Rulesets",
    scopes: ["com.cloudflare.api.account"],
    label: "account_rulesets_write",
    type: "edit",
    rowId: 1181,
    parsedName: "Account Rulesets",
  },
  {
    id: "c1fde68c7bcc44588cbb6ddbc16d6480",
    name: "account_settings",
    description:
      "Grants read access to Account resources, account membership, and account level features",
    scopes: ["com.cloudflare.api.account"],
    label: "account_settings_read",
    type: "read",
    rowId: 1182,
    parsedName: "Account Settings",
  },
  {
    id: "1af1fa2adc104452b74a9a3364202f20",
    name: "account_settings",
    description:
      "Grants write access to Account resources, account membership, and account level features",
    scopes: ["com.cloudflare.api.account"],
    label: "account_settings_write",
    type: "edit",
    rowId: 1183,
    parsedName: "Account Settings",
  },
  {
    id: "56b2af4817c84ad99187911dc3986c23",
    name: "account_waf",
    description: "Grants read access to Account WAF",
    scopes: ["com.cloudflare.api.account"],
    label: "account_waf_read",
    type: "read",
    rowId: 1184,
    parsedName: "Account WAF",
  },
  {
    id: "cde8c82463b6414ca06e46b9633f52a6",
    name: "account_waf",
    description: "grants write access to account waf",
    scopes: ["com.cloudflare.api.account"],
    label: "account_waf_write",
    type: "edit",
    rowId: 1185,
    parsedName: "Account WAF",
  },
  {
    id: "a7a233f9604845c787d4c8c39ac09c21",
    name: "account_ssl_and_certificates",
    description:
      "Grants read access to SSL MTLS certificates or Certificate Store",
    scopes: ["com.cloudflare.api.account"],
    label: "account_ssl_and_certificates_read",
    type: "read",
    rowId: 1186,
    parsedName: "Account: SSL and Certificates",
  },
  {
    id: "db37e5f1cb1a4e1aabaef8deaea43575",
    name: "account_ssl_and_certificates",
    description:
      "Grants read and write access to SSL MTLS certificates or Certificate Store",
    scopes: ["com.cloudflare.api.account"],
    label: "account_ssl_and_certificates_write",
    type: "edit",
    rowId: 1187,
    parsedName: "Account: SSL and Certificates",
  },
  {
    id: "d07270cea5484b08ad6440c985af2148",
    name: "address_maps",
    description: "Grants read access to Address Maps",
    scopes: ["com.cloudflare.api.account"],
    label: "address_maps_read",
    type: "read",
    rowId: 1188,
    parsedName: "Address Maps",
  },
  {
    id: "6ffe7f4299db4d4cb54f64e0eb12a456",
    name: "address_maps",
    description: "Grants write access to Address Maps",
    scopes: ["com.cloudflare.api.account"],
    label: "address_maps_write",
    type: "edit",
    rowId: 1189,
    parsedName: "Address Maps",
  },
  {
    id: "f3604047d46144d2a3e9cf4ac99d7f16",
    name: "request_tracer",
    description: "Allows read access to request tracer API",
    scopes: ["com.cloudflare.api.account"],
    label: "request_tracer_read",
    type: "read",
    rowId: 1190,
    parsedName: "Allow Request Tracer",
  },
  {
    id: "9c88f9c5bce24ce7af9a958ba9c504db",
    name: "analytics",
    description: "Grants read access to analytics",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "analytics_read",
    type: "read",
    rowId: 1191,
    parsedName: "Analytics",
  },
  {
    id: "094547ab6e77498c8c4dfa87fadd5c51",
    name: "apps",
    description: "Grants full access to Cloudflare Apps",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "apps_write",
    type: "edit",
    rowId: 1192,
    parsedName: "Apps",
  },
  {
    id: "efea2ab8357b47888938f101ae5e053f",
    name: "argotunnel",
    description: "Grants access to view Argo Tunnels",
    scopes: ["com.cloudflare.api.account"],
    label: "argotunnel_read",
    type: "read",
    rowId: 1193,
    parsedName: "Cloudflare Tunnel",
  },
  {
    id: "c07321b023e944ff818fec44d8203567",
    name: "argotunnel",
    description: "Grants access to create and delete Argo Tunnels",
    scopes: ["com.cloudflare.api.account"],
    label: "argotunnel_write",
    type: "edit",
    rowId: 1194,
    parsedName: "Cloudflare Tunnel",
  },
  {
    id: "7cf72faf220841aabcfdfab81c43c4f6",
    name: "billing",
    description:
      "Grants read access to billing profile, subscriptions, usage data and access to fetch invoices and entitlements",
    scopes: ["com.cloudflare.api.account"],
    label: "billing_read",
    type: "read",
    rowId: 1195,
    parsedName: "Billing",
  },
  {
    id: "6c80e02421494afc9ae14414ed442632",
    name: "billing",
    description:
      "Grants write access to billing profile, subscriptions, and access to fetch invoices and entitlements",
    scopes: ["com.cloudflare.api.account"],
    label: "billing_write",
    type: "edit",
    rowId: 1196,
    parsedName: "Billing",
  },
  {
    id: "51be404b56244056868226263a44a632",
    name: "bot_management_feedback",
    description: "Grants read access to BOT Management Feedback Reports",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "bot_management_feedback_read",
    type: "read",
    rowId: 1197,
    parsedName: "Bot Management Feedback",
  },
  {
    id: "2002629aaff0454085bf5a201ed70a72",
    name: "bot_management_feedback",
    description: "Grants write access to BOT Management Feedback Reports",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "bot_management_feedback_write",
    type: "edit",
    rowId: 1198,
    parsedName: "Bot Management Feedback",
  },
  {
    id: "07bea2220b2343fa9fae15656c0d8e88",
    name: "bot_management",
    description: "Grants read access to BOT Management",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "bot_management_read",
    type: "read",
    rowId: 1199,
    parsedName: "Bot Management",
  },
  {
    id: "3b94c49258ec4573b06d51d99b6416c0",
    name: "bot_management",
    description: "Grants write access to BOT Management",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "bot_management_write",
    type: "edit",
    rowId: 1200,
    parsedName: "Bot Management",
  },
  {
    id: "374b03fa229f4eb6b011bb1cd7f235ee",
    name: "browser_rendering",
    description: "Grants read access to Browser Rendering API",
    scopes: ["com.cloudflare.api.account"],
    label: "browser_rendering_read",
    type: "read",
    rowId: 1201,
    parsedName: "Browser Rendering",
  },
  {
    id: "adddda876faa4a0590f1b23a038976e4",
    name: "browser_rendering",
    description: "Grants write access to Browser Rendering API",
    scopes: ["com.cloudflare.api.account"],
    label: "browser_rendering_write",
    type: "edit",
    rowId: 1202,
    parsedName: "Browser Rendering",
  },
  {
    id: "e17beae8b8cb423a99b1730f21238bed",
    name: "cache",
    description: "Grants access to purge cache",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "cache_purge",
    type: "purge",
    rowId: 1203,
    parsedName: "Cache Purge",
  },
  {
    id: "3245da1cf36c45c3847bb9b483c62f97",
    name: "cache_settings",
    description: "Grants read access to cache settings phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "cache_settings_read",
    type: "read",
    rowId: 1204,
    parsedName: "Cache Rules",
  },
  {
    id: "9ff81cbbe65c400b97d92c3c1033cab6",
    name: "cache_settings",
    description: "Grants write access to cache settings phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "cache_settings_write",
    type: "edit",
    rowId: 1205,
    parsedName: "Cache Rules",
  },
  {
    id: "686ab9a8b3854f25a1474f302d14b68d",
    name: "calls",
    description: "Grants read access to Calls configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "calls_read",
    type: "read",
    rowId: 1206,
    parsedName: "Cloudflare Calls",
  },
  {
    id: "b711942448db4b0aace44d1312f9fdb0",
    name: "calls",
    description: "Grants read/write access to Calls configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "calls_write",
    type: "edit",
    rowId: 1207,
    parsedName: "Cloudflare Calls",
  },
  {
    id: "9ade9cfc8f8949bcb2371be2f0ec8db1",
    name: "chinanetwork_steering",
    description: "Grants read access to China Network Steering",
    scopes: ["com.cloudflare.api.account"],
    label: "chinanetwork_steering_read",
    type: "read",
    rowId: 1208,
    parsedName: "China Network Steering",
  },
  {
    id: "c6f6338ceae545d0b90daaa1fed855e6",
    name: "chinanetwork_steering",
    description: "Grants write access to China Network Steering",
    scopes: ["com.cloudflare.api.account"],
    label: "chinanetwork_steering_write",
    type: "edit",
    rowId: 1209,
    parsedName: "China Network Steering",
  },
  {
    id: "0661ff47aa3a4786beab3b8128e0cd24",
    name: "cloud_connector",
    description: "Grants read access to Cloud Connector",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "cloud_connector_read",
    type: "read",
    rowId: 1210,
    parsedName: "Cloud Connector",
  },
  {
    id: "eafd71286d0e4fdca404a7b4d203c5c9",
    name: "cloud_connector",
    description: "Grants write access to Cloud Connector",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "cloud_connector_write",
    type: "edit",
    rowId: 1211,
    parsedName: "Cloud Connector",
  },
  {
    id: "9e5a9912439940fca5898b5b8dc6d1a5",
    name: "cloud_email_security",
    description: "Grants read access to Cloudflare Cloud Email Security",
    scopes: ["com.cloudflare.api.account"],
    label: "cloud_email_security_read",
    type: "read",
    rowId: 1212,
    parsedName: "Email Security",
  },
  {
    id: "a3567c13e074447fb101babac3463566",
    name: "cloud_email_security",
    description: "Grants write access to Cloudflare Cloud Email Security",
    scopes: ["com.cloudflare.api.account"],
    label: "cloud_email_security_write",
    type: "edit",
    rowId: 1213,
    parsedName: "Email Security",
  },
  {
    id: "65ec50cbde3d4c838bbe7500024d5745",
    name: "cloudchamber",
    description: "Grants read access to Cloudchamber deployments",
    scopes: ["com.cloudflare.api.account"],
    label: "cloudchamber_read",
    type: "read",
    rowId: 1214,
    parsedName: "Cloudchamber",
  },
  {
    id: "26ce6c7d18a346528e7b905d5e269866",
    name: "cloudchamber",
    description: "Grants write access to Cloudchamber deployments",
    scopes: ["com.cloudflare.api.account"],
    label: "cloudchamber_write",
    type: "edit",
    rowId: 1215,
    parsedName: "Cloudchamber",
  },
  {
    id: "00ec19a0d4fa4e4aae23b50bf04c0630",
    name: "teams_cds_compute_account",
    description:
      "Grants read access to Cloudflare CDS compute account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_cds_compute_account_read",
    type: "read",
    rowId: 1216,
    parsedName: "Cloudflare CDS Compute Account",
  },
  {
    id: "9bf884ba0de445dab37ea4a3e1a2c9f1",
    name: "teams_cds_compute_account",
    description:
      "Grants write access to Cloudflare CDS compute account resources",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_cds_compute_account_write",
    type: "edit",
    rowId: 1217,
    parsedName: "Cloudflare CDS Compute Account",
  },
  {
    id: "3a1e1ef09dd34271bb44fc4c6a419952",
    name: "teams",
    description: "Grants access to Cloudflare DEX",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_dex",
    type: "dex",
    rowId: 1218,
    parsedName: "Zero Trust",
  },
  {
    id: "3b376e0aa52c41cbb6afc9cab945afa8",
    name: "teams_dex",
    description: "Grants read access to Cloudflare DEX",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_dex_read",
    type: "read",
    rowId: 1219,
    parsedName: "Zero Trust",
  },
  {
    id: "92c8dcd551cc42a6a57a54e8f8d3f3e3",
    name: "teams_dex",
    description: "Grants full access to Cloudflare DEX",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_dex_write",
    type: "edit",
    rowId: 1220,
    parsedName: "Zero Trust",
  },
  {
    id: "07cf1c1952a84b13b2cd542f3d2f29ab",
    name: "teams_connectors",
    description: "Grants read access to Cloudflare One Connectors",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_connectors_read",
    type: "read",
    rowId: 1221,
    parsedName: "Cloudflare One Connectors",
  },
  {
    id: "a7030c9c98d544e092d8b099fabb1f06",
    name: "teams_connectors",
    description: "Grants write access to Cloudflare One Connectors",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_connectors_write",
    type: "edit",
    rowId: 1222,
    parsedName: "Cloudflare One Connectors",
  },
  {
    id: "4f1276d1e7e34c32a5012bbe02ece86d",
    name: "teams_networks",
    description: "Grants read access to Cloudflare One Networks",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_networks_read",
    type: "read",
    rowId: 1223,
    parsedName: "Cloudflare One Networks",
  },
  {
    id: "e2980d9241cf4939bbbd74fdc43b9651",
    name: "teams_networks",
    description: "Grants write access to Cloudflare One Networks",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_networks_write",
    type: "edit",
    rowId: 1224,
    parsedName: "Cloudflare One Networks",
  },
  {
    id: "1cd960c063a0448481343372c963d8c7",
    name: "teams_connector_warp",
    description: "Grants read access to Warp Connectors",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_connector_warp_read",
    type: "read",
    rowId: 1225,
    parsedName: "Cloudflare One Connector: WARP",
  },
  {
    id: "5b5c774a5d174ca88d046c8889648b3f",
    name: "teams_connector_warp",
    description: "Grants write access to Warp Connectors",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_connector_warp_write",
    type: "edit",
    rowId: 1226,
    parsedName: "Cloudflare One Connector: WARP",
  },
  {
    id: "c1968d31028d4239976ec3bc4750bbf6",
    name: "teams_connector_cloudflared",
    description: "Grants read access to cloudflared Connectors",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_connector_cloudflared_read",
    type: "read",
    rowId: 1227,
    parsedName: "Cloudflare One Connector: cloudflared",
  },
  {
    id: "037b9e348b3b42d4b46ea2fcb1cfb3e7",
    name: "teams_connector_cloudflared",
    description: "Grants write access to cloudflared Connectors",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_connector_cloudflared_write",
    type: "edit",
    rowId: 1228,
    parsedName: "Cloudflare One Connector: cloudflared",
  },
  {
    id: "f5d857f67f144e3c8bacea88c17d4a13",
    name: "teams_pii",
    description: "Can access Cloudflare Zero Trust PII.",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_pii_read",
    type: "read",
    rowId: 1229,
    parsedName: "Zero Trust: PII",
  },
  {
    id: "cf9353ed7978436e8fb20c03fce26449",
    name: "cloudforce_one",
    description: "Grants read access to Cloudforce One",
    scopes: ["com.cloudflare.api.account"],
    label: "cloudforce_one_read",
    type: "read",
    rowId: 1230,
    parsedName: "Cloudforce One",
  },
  {
    id: "677767156f294485b497a8f103172e7d",
    name: "cloudforce_one",
    description: "Grants read access to Cloudforce One",
    scopes: ["com.cloudflare.api.account"],
    label: "cloudforce_one_write",
    type: "edit",
    rowId: 1231,
    parsedName: "Cloudforce One",
  },
  {
    id: "20e5ea084b2f491c86b8d8d90abff905",
    name: "config_settings",
    description: "Grants read access to config settings phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "config_settings_read",
    type: "read",
    rowId: 1232,
    parsedName: "Config Rules",
  },
  {
    id: "06f0526e6e464647bd61b63c54935235",
    name: "config_settings",
    description: "Grants write access to config settings phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "config_settings_write",
    type: "edit",
    rowId: 1233,
    parsedName: "Config Rules",
  },
  {
    id: "eeffa4d16812430cb4a0ae9e7f46fc24",
    name: "constellation",
    description: "Grants read access to Constellation configuration and models",
    scopes: ["com.cloudflare.api.account"],
    label: "constellation_read",
    type: "read",
    rowId: 1234,
    parsedName: "Constellation",
  },
  {
    id: "7c81856725af47ce89a790d5fb36f362",
    name: "constellation",
    description:
      "Grants write access to Constellation configuration and models",
    scopes: ["com.cloudflare.api.account"],
    label: "constellation_write",
    type: "edit",
    rowId: 1235,
    parsedName: "Constellation",
  },
  {
    id: "a2b55cd504d44ef18b7ba6a7f2b8fbb1",
    name: "custom_errors",
    description: "Grants read access to custom errors phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "custom_errors_read",
    type: "read",
    rowId: 1236,
    parsedName: "Custom Error Rules",
  },
  {
    id: "a9dba34cf5814d4ab2007b4ada0045bd",
    name: "custom_errors",
    description: "Grants write access to custom errors phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "custom_errors_write",
    type: "edit",
    rowId: 1237,
    parsedName: "Custom Error Rules",
  },
  {
    id: "a2431ca73b7d41f99c53303027392586",
    name: "custom_pages",
    description: "Grants read access to custom pages",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "custom_pages_read",
    type: "read",
    rowId: 1238,
    parsedName: "Custom Pages",
  },
  {
    id: "c244ec076974430a88bda1cdd992d0d9",
    name: "custom_pages",
    description: "Grants write access to custom pages",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "custom_pages_write",
    type: "edit",
    rowId: 1239,
    parsedName: "Custom Pages",
  },
  {
    id: "192192df92ee43ac90f2aeeffce67e35",
    name: "d1",
    description: "Grants read access to D1 configuration and SQL queries",
    scopes: ["com.cloudflare.api.account"],
    label: "d1_read",
    type: "read",
    rowId: 1240,
    parsedName: "D1",
  },
  {
    id: "09b2857d1c31407795e75e3fed8617a1",
    name: "d1",
    description: "Grants write access to D1 configuration and SQL queries",
    scopes: ["com.cloudflare.api.account"],
    label: "d1_write",
    type: "edit",
    rowId: 1241,
    parsedName: "D1",
  },
  {
    id: "dee7c22a57674abea8f942110b094717",
    name: "ddos_botnet_feed",
    description: "Grants read access to Botnet Feed reports",
    scopes: ["com.cloudflare.api.account"],
    label: "ddos_botnet_feed_read",
    type: "read",
    rowId: 1242,
    parsedName: "DDoS Botnet Feed",
  },
  {
    id: "0caa90c9b186447397c8b00358d34a76",
    name: "ddos_botnet_feed",
    description: "Grants write access to Botnet Feed configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "ddos_botnet_feed_write",
    type: "edit",
    rowId: 1243,
    parsedName: "DDoS Botnet Feed",
  },
  {
    id: "af1c363c35ba45b9a8c682ae50eb3f99",
    name: "ddos_protection",
    description: "Grants read access to DDoS protection",
    scopes: ["com.cloudflare.api.account"],
    label: "ddos_protection_read",
    type: "read",
    rowId: 1244,
    parsedName: "DDoS Protection",
  },
  {
    id: "d44ed14bcc4340b194d3824d60edad3f",
    name: "ddos_protection",
    description: "Grants write access to DDoS protection",
    scopes: ["com.cloudflare.api.account"],
    label: "ddos_protection_write",
    type: "edit",
    rowId: 1245,
    parsedName: "DDoS Protection",
  },
  {
    id: "5f48a472240a4b489a21d43bd19a06e1",
    name: "dns_firewall",
    description: "Grants read access to DNS Firewall",
    scopes: ["com.cloudflare.api.account"],
    label: "dns_firewall_read",
    type: "read",
    rowId: 1246,
    parsedName: "DNS Firewall",
  },
  {
    id: "da6d2d6f2ec8442eaadda60d13f42bca",
    name: "dns_firewall",
    description: "Grants write access to DNS Firewall",
    scopes: ["com.cloudflare.api.account"],
    label: "dns_firewall_write",
    type: "edit",
    rowId: 1247,
    parsedName: "DNS Firewall",
  },
  {
    id: "82e64a83756745bbbb1c9c2701bf816b",
    name: "dns",
    description: "Grants read access to DNS",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "dns_read",
    type: "read",
    rowId: 1248,
    parsedName: "DNS",
  },
  {
    id: "95d69e8d6d5144bfb0923667355d9f11",
    name: "dns_view",
    description: "Grants read access to DNS Views",
    scopes: ["com.cloudflare.api.account"],
    label: "dns_view_read",
    type: "read",
    rowId: 1249,
    parsedName: "DNS Views",
  },
  {
    id: "5b7aedd821a548b9bf5a2acabbce98c7",
    name: "dns_view",
    description: "Grants write access to DNS Views",
    scopes: ["com.cloudflare.api.account"],
    label: "dns_view_write",
    type: "edit",
    rowId: 1250,
    parsedName: "DNS Views",
  },
  {
    id: "4755a26eedb94da69e1066d98aa820be",
    name: "dns",
    description: "Grants write access to DNS",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "dns_write",
    type: "edit",
    rowId: 1251,
    parsedName: "DNS",
  },
  {
    id: "e199d584e69344eba202452019deafe3",
    name: "zone_disable_esc",
    description: "Grants read access to Cloudflare Disable ESC",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_disable_esc_read",
    type: "read",
    rowId: 1252,
    parsedName: "Disable ESC",
  },
  {
    id: "29eefa0805f94fdfae2b058b5b52f319",
    name: "account_disable_esc",
    description: "Grants read access to Cloudflare Disable ESC",
    scopes: ["com.cloudflare.api.account"],
    label: "account_disable_esc_read",
    type: "read",
    rowId: 1253,
    parsedName: "Disable ESC",
  },
  {
    id: "9110d9dd749e464fb9f3961a2064efc5",
    name: "zone_disable_esc",
    description: "Grants write access to Cloudflare Disable ESC",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_disable_esc_write",
    type: "edit",
    rowId: 1254,
    parsedName: "Disable ESC",
  },
  {
    id: "18555e39c5ba40d284dde87eda845a90",
    name: "account_disable_esc",
    description: "Grants write access to Cloudflare Disable ESC",
    scopes: ["com.cloudflare.api.account"],
    label: "account_disable_esc_write",
    type: "edit",
    rowId: 1255,
    parsedName: "Disable ESC",
  },
  {
    id: "f0235726de25444a84f704b7c93afadf",
    name: "api_gateway",
    description:
      "Grants full access to API-Gateway Management (including API Shield)",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "api_gateway_write",
    type: "edit",
    rowId: 1256,
    parsedName: "API Gateway",
  },
  {
    id: "6ced5d0d69b1422396909a62c38ab41b",
    name: "api_gateway",
    description:
      "Grants read access to API-Gateway Management (including API Shield)",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "api_gateway_read",
    type: "read",
    rowId: 1257,
    parsedName: "API Gateway",
  },
  {
    id: "6134079371904d8ebd77931c8ca07e50",
    name: "domain_page",
    description: "Grants write access to Page Shield",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "domain_page_shield",
    type: "shield",
    rowId: 1258,
    parsedName: "Page Shield",
  },
  {
    id: "945315185a8f40518bf3e9e6d0bee126",
    name: "domain_page_shield",
    description: "Grants read access to Page Shield",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "domain_page_shield_read",
    type: "read",
    rowId: 1259,
    parsedName: "Page Shield",
  },
  {
    id: "d8e12db741544d1586ec1d6f5d3c7786",
    name: "dynamic_redirect",
    description: "Grants read access to Dynamic URL Redirect",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "dynamic_redirect_read",
    type: "read",
    rowId: 1260,
    parsedName: "Single Redirect",
  },
  {
    id: "74e1036f577a48528b78d2413b40538d",
    name: "dynamic_redirect",
    description: "Grants write access to Dynamic URL Redirect",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "dynamic_redirect_write",
    type: "edit",
    rowId: 1261,
    parsedName: "Single Redirect",
  },
  {
    id: "5272e56105d04b5897466995b9bd4643",
    name: "email_routing_address",
    description: "Grants read access to Email Routing target addresses\n",
    scopes: ["com.cloudflare.api.account"],
    label: "email_routing_address_read",
    type: "read",
    rowId: 1262,
    parsedName: "Email Routing Addresses",
  },
  {
    id: "e4589eb09e63436686cd64252a3aebeb",
    name: "email_routing_address",
    description: "Grants full access to Email Routing target addresses\n",
    scopes: ["com.cloudflare.api.account"],
    label: "email_routing_address_write",
    type: "edit",
    rowId: 1263,
    parsedName: "Email Routing Addresses",
  },
  {
    id: "1b600d9d8062443e986a973f097e728a",
    name: "email_routing_rule",
    description: "Grants read access to Email Routing rules\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "email_routing_rule_read",
    type: "read",
    rowId: 1264,
    parsedName: "Email Routing Rules",
  },
  {
    id: "79b3ec0d10ce4148a8f8bdc0cc5f97f2",
    name: "email_routing_rule",
    description: "Grants full access to Email Routing rules\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "email_routing_rule_write",
    type: "edit",
    rowId: 1265,
    parsedName: "Email Routing Rules",
  },
  {
    id: "1047880d37b649b49db4a504a245896f",
    name: "email_security_dmarcreports",
    description: "Grants read access to Email Security dmarc reports\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "email_security_dmarcreports_read",
    type: "read",
    rowId: 1266,
    parsedName: "Dmarc Management",
  },
  {
    id: "2eee71c9364c4cacaf469e8370f09056",
    name: "email_security_dmarcreports",
    description: "Grants full access to Email Security dmarc reports\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "email_security_dmarcreports_write",
    type: "edit",
    rowId: 1267,
    parsedName: "Dmarc Management",
  },
  {
    id: "4ec32dfcb35641c5bb32d5ef1ab963b4",
    name: "firewall_services",
    description: "Grants read access to Firewall resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "firewall_services_read",
    type: "read",
    rowId: 1268,
    parsedName: "Firewall Services",
  },
  {
    id: "43137f8d07884d3198dc0ee77ca6e79b",
    name: "firewall_services",
    description: "Grants write access to Firewall resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "firewall_services_write",
    type: "edit",
    rowId: 1269,
    parsedName: "Firewall Services",
  },
  {
    id: "0d24e472a9654642a97df736e8b0d980",
    name: "fraud_detection",
    description: "Grants read access to Fraud Detection",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "fraud_detection_read",
    type: "read",
    rowId: 1270,
    parsedName: "Fraud Detection",
  },
  {
    id: "685f9605fd4e44ec937b6a0db658e629",
    name: "fraud_detection",
    description: "Grants write access to Fraud Detection",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "fraud_detection_write",
    type: "edit",
    rowId: 1271,
    parsedName: "Fraud Detection",
  },
  {
    id: "6b60a5a87cae475da7e76e77e4209dd5",
    name: "http_applications",
    description: "Grants read-only access to HTTP Applications",
    scopes: ["com.cloudflare.api.account"],
    label: "http_applications_read",
    type: "read",
    rowId: 1272,
    parsedName: "HTTP Applications",
  },
  {
    id: "4736c02a9f224c8196ae5b127beae78c",
    name: "http_applications",
    description: "Grants full access to HTTP Applications",
    scopes: ["com.cloudflare.api.account"],
    label: "http_applications_write",
    type: "edit",
    rowId: 1273,
    parsedName: "HTTP Applications",
  },
  {
    id: "c49f8d15f9f44885a544d945ef5aa6ae",
    name: "http_ddos_managed_ruleset",
    description: "Grants read access to HTTP DDoS Managed Ruleset",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "http_ddos_managed_ruleset_read",
    type: "read",
    rowId: 1274,
    parsedName: "HTTP DDoS Managed Ruleset",
  },
  {
    id: "b88a3aa889474524bccea5cf18f122bf",
    name: "http_ddos_managed_ruleset",
    description: "Grants write access to HTTP DDoS Managed Ruleset",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "http_ddos_managed_ruleset_write",
    type: "edit",
    rowId: 1275,
    parsedName: "HTTP DDoS Managed Ruleset",
  },
  {
    id: "fac65912d42144aa86b7dd33281bf79e",
    name: "healthcheck",
    description: "Grants read access to Health Checks",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "healthcheck_read",
    type: "read",
    rowId: 1276,
    parsedName: "Health Checks",
  },
  {
    id: "e0dc25a0fbdf4286b1ea100e3256b0e3",
    name: "healthcheck",
    description: "Grants write access to Health Checks",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "healthcheck_write",
    type: "edit",
    rowId: 1277,
    parsedName: "Health Checks",
  },
  {
    id: "4d62ccf834df44808bc9283d65c4e4e9",
    name: "query_cache",
    description: "Grants read access to Hyperdrive configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "query_cache_read",
    type: "read",
    rowId: 1278,
    parsedName: "Hyperdrive",
  },
  {
    id: "721b2f51fba74871bd361de65aeb7e03",
    name: "query_cache",
    description: "Grants write access to Hyperdrive configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "query_cache_write",
    type: "edit",
    rowId: 1279,
    parsedName: "Hyperdrive",
  },
  {
    id: "212c9ff247b9406d990c017482afb3a5",
    name: "iot",
    description: "Grants read access to IOT devices",
    scopes: ["com.cloudflare.api.account"],
    label: "iot_read",
    type: "read",
    rowId: 1280,
    parsedName: "IOT",
  },
  {
    id: "865ebd55bc6d4b109de6813eccfefd13",
    name: "iot",
    description: "Grants full access to IOT devices",
    scopes: ["com.cloudflare.api.account"],
    label: "iot_write",
    type: "edit",
    rowId: 1281,
    parsedName: "IOT",
  },
  {
    id: "e763fae6ee95443b8f56f19213c5f2a5",
    name: "ip_prefix_bgp_on_demand",
    description: "Grants access to read ip prefix bgp configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "ip_prefix_bgp_on_demand_read",
    type: "read",
    rowId: 1282,
    parsedName: "IP Prefixes: BGP On Demand",
  },
  {
    id: "2ae23e4939d54074b7d252d27ce75a77",
    name: "ip_prefix_bgp_on_demand",
    description: "Grants access to read and change ip prefix bgp configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "ip_prefix_bgp_on_demand_write",
    type: "edit",
    rowId: 1283,
    parsedName: "IP Prefixes: BGP On Demand",
  },
  {
    id: "27beb7f8333b41e2b946f0e23cd8091e",
    name: "ip_prefix",
    description: "Grants access to read ip prefix settings",
    scopes: ["com.cloudflare.api.account"],
    label: "ip_prefix_read",
    type: "read",
    rowId: 1284,
    parsedName: "IP Prefixes",
  },
  {
    id: "92b8234e99f64e05bbbc59e1dc0f76b6",
    name: "ip_prefix",
    description: "Grants access to read/write ip prefix settings",
    scopes: ["com.cloudflare.api.account"],
    label: "ip_prefix_write",
    type: "edit",
    rowId: 1285,
    parsedName: "IP Prefixes",
  },
  {
    id: "0cf6473ad41449e7b7b743d14fc20c60",
    name: "images",
    description: "Grants read access to Images",
    scopes: ["com.cloudflare.api.account"],
    label: "images_read",
    type: "read",
    rowId: 1286,
    parsedName: "Cloudflare Images",
  },
  {
    id: "618ec6c64a3a42f8b08bdcb147ded4e4",
    name: "images",
    description: "Grants write access to upload Images",
    scopes: ["com.cloudflare.api.account"],
    label: "images_write",
    type: "edit",
    rowId: 1287,
    parsedName: "Cloudflare Images",
  },
  {
    id: "c6f97eeee13345db8cc00af0953a42de",
    name: "integration",
    description: "Grants write access to integrations",
    scopes: ["com.cloudflare.api.account"],
    label: "integration_write",
    type: "edit",
    rowId: 1288,
    parsedName: "Integrations",
  },
  {
    id: "df1577df30ee46268f9470952d7b0cdf",
    name: "intel",
    description: "Grants read access to Intel API",
    scopes: ["com.cloudflare.api.account"],
    label: "intel_read",
    type: "read",
    rowId: 1289,
    parsedName: "Intel",
  },
  {
    id: "92209474242d459690e2cdb1985eaa6c",
    name: "intel",
    description: "Grants write access to Intel API",
    scopes: ["com.cloudflare.api.account"],
    label: "intel_write",
    type: "edit",
    rowId: 1290,
    parsedName: "Intel",
  },
  {
    id: "4657621393f94f83b8ef94adba382e48",
    name: "l4_ddos_managed_ruleset",
    description: "Grants read access to L4 DDoS Managed Ruleset",
    scopes: ["com.cloudflare.api.account"],
    label: "l4_ddos_managed_ruleset_read",
    type: "read",
    rowId: 1291,
    parsedName: "L3/4 DDoS Managed Ruleset",
  },
  {
    id: "7a4c3574054a4d0ba7c692893ba8bdd4",
    name: "l4_ddos_managed_ruleset",
    description: "Grants write access to L4 DDoS Managed Ruleset",
    scopes: ["com.cloudflare.api.account"],
    label: "l4_ddos_managed_ruleset_write",
    type: "edit",
    rowId: 1292,
    parsedName: "L3/4 DDoS Managed Ruleset",
  },
  {
    id: "59059f0c977b44f8b1c18e0aaf91c369",
    name: "load_balancers_account",
    description:
      "Grants read access to account load balancers and associated resources",
    scopes: ["com.cloudflare.api.account"],
    label: "load_balancers_account_read",
    type: "read",
    rowId: 1293,
    parsedName: "Load Balancing: Account Load Balancers",
  },
  {
    id: "419ec42810af4659ade77716dbe47bc6",
    name: "load_balancers_account",
    description:
      "Grants write access to account load balancers and associated resources",
    scopes: ["com.cloudflare.api.account"],
    label: "load_balancers_account_write",
    type: "edit",
    rowId: 1294,
    parsedName: "Load Balancing: Account Load Balancers",
  },
  {
    id: "e9a975f628014f1d85b723993116f7d5",
    name: "load_balancers",
    description:
      "Grants read access to load balancers and associated resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "load_balancers_read",
    type: "read",
    rowId: 1295,
    parsedName: "Load Balancers",
  },
  {
    id: "6d7f2f5f5b1d4a0e9081fdc98d432fd1",
    name: "load_balancers",
    description:
      "Grants write access to load balancers and associated resources",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "load_balancers_write",
    type: "edit",
    rowId: 1296,
    parsedName: "Load Balancers",
  },
  {
    id: "9d24387c6e8544e2bc4024a03991339f",
    name: "load_balancing_monitors_and_pools",
    description: "Grants read access to account level load balancer resources",
    scopes: ["com.cloudflare.api.account"],
    label: "load_balancing_monitors_and_pools_read",
    type: "read",
    rowId: 1297,
    parsedName: "Load Balancing: Monitors And Pools",
  },
  {
    id: "d2a1802cc9a34e30852f8b33869b2f3c",
    name: "load_balancing_monitors_and_pools",
    description: "Grants write access to account level load balancer resources",
    scopes: ["com.cloudflare.api.account"],
    label: "load_balancing_monitors_and_pools_write",
    type: "edit",
    rowId: 1298,
    parsedName: "Load Balancing: Monitors And Pools",
  },
  {
    id: "6a315a56f18441e59ed03352369ae956",
    name: "account_logs",
    description: "Grants read access to logs and logpush jobs",
    scopes: ["com.cloudflare.api.account"],
    label: "account_logs_read",
    type: "read",
    rowId: 1299,
    parsedName: "Account Logs",
  },
  {
    id: "c4a30cd58c5d42619c86a3c36c441e2d",
    name: "logs",
    description: "Grants read access to logs and logpush jobs",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "logs_read",
    type: "read",
    rowId: 1300,
    parsedName: "Logs",
  },
  {
    id: "96163bd1b0784f62b3e44ed8c2ab1eb6",
    name: "account_logs",
    description: "Grants write access to logpush jobs",
    scopes: ["com.cloudflare.api.account"],
    label: "account_logs_write",
    type: "edit",
    rowId: 1301,
    parsedName: "Account Logs",
  },
  {
    id: "3e0b5820118e47f3922f7c989e673882",
    name: "logs",
    description: "Grants write access to logpush jobs",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "logs_write",
    type: "edit",
    rowId: 1302,
    parsedName: "Logs",
  },
  {
    id: "3a46c728a0a040d5a65cd8e2f3bc6935",
    name: "pcaps_api",
    description: "Grants read access to Packet Captures",
    scopes: ["com.cloudflare.api.account"],
    label: "pcaps_api_read",
    type: "read",
    rowId: 1303,
    parsedName: "Magic Firewall Packet Captures",
  },
  {
    id: "4ea7d6421801452dbf07cef853a5ef39",
    name: "pcaps_api",
    description: "Grants write access to Packet Captures",
    scopes: ["com.cloudflare.api.account"],
    label: "pcaps_api_write",
    type: "edit",
    rowId: 1304,
    parsedName: "Magic Firewall Packet Captures",
  },
  {
    id: "02b71f12bb0748e9af8126494e181342",
    name: "magic_firewall",
    description: "Grants read access to Magic Firewall",
    scopes: ["com.cloudflare.api.account"],
    label: "magic_firewall_read",
    type: "read",
    rowId: 1305,
    parsedName: "Magic Firewall",
  },
  {
    id: "8bd1dac84d3d43e7bfb43145f010a15c",
    name: "magic_firewall",
    description: "Grants write access to Magic Firewall",
    scopes: ["com.cloudflare.api.account"],
    label: "magic_firewall_write",
    type: "edit",
    rowId: 1306,
    parsedName: "Magic Firewall",
  },
  {
    id: "8e6ed1ef6e864ad0ae477ceffa5aa5eb",
    name: "fbm",
    description: "Grants admin access to MNM settings",
    scopes: ["com.cloudflare.api.account"],
    label: "fbm_admin",
    type: "admin",
    rowId: 1307,
    parsedName: "Magic Network Monitoring",
  },
  {
    id: "3d85e9514f944bb4912c5871d92e5af5",
    name: "fbm",
    description: "Grants read access to MNM config and rules",
    scopes: ["com.cloudflare.api.account"],
    label: "fbm_read",
    type: "read",
    rowId: 1308,
    parsedName: "Magic Network Monitoring",
  },
  {
    id: "09c77baecb6341a2b1ca2c62b658d290",
    name: "fbm",
    description:
      "Grants write access to MNM rules and update access to account settings",
    scopes: ["com.cloudflare.api.account"],
    label: "fbm_write",
    type: "edit",
    rowId: 1309,
    parsedName: "Magic Network Monitoring",
  },
  {
    id: "967ecf860a244dd1911a0331a0af582a",
    name: "magic_transit",
    description:
      "Grants read access to manage a user's Magic Transit prefixes,",
    scopes: ["com.cloudflare.api.account"],
    label: "magic_transit_read",
    type: "read",
    rowId: 1310,
    parsedName: "Magic Transit",
  },
  {
    id: "0bc09a3cd4b54605990df4e307f138e1",
    name: "magic_transit",
    description:
      "Grants write access to manage a user's Magic Transit prefixes,",
    scopes: ["com.cloudflare.api.account"],
    label: "magic_transit_write",
    type: "edit",
    rowId: 1311,
    parsedName: "Magic Transit",
  },
  {
    id: "319f5059d33a410da0fac4d35a716157",
    name: "managed_headers",
    description: "Grants read access to managed headers phases",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "managed_headers_read",
    type: "read",
    rowId: 1312,
    parsedName: "Managed Headers",
  },
  {
    id: "0fd9d56bc2da43ad8ea22d610dd8cab1",
    name: "managed_headers",
    description: "Grants write access to managed headers phases",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "managed_headers_write",
    type: "edit",
    rowId: 1313,
    parsedName: "Managed Headers",
  },
  {
    id: "429a068902904c5a9ed9fc267c67da9a",
    name: "mass_url_redirects",
    description: "Grants read access to Mass URL Redirect",
    scopes: ["com.cloudflare.api.account"],
    label: "mass_url_redirects_read",
    type: "read",
    rowId: 1314,
    parsedName: "Bulk URL Redirects",
  },
  {
    id: "abe78e2276664f4db588c1f675a77486",
    name: "mass_url_redirects",
    description: "Grants write access to Mass URL Redirect",
    scopes: ["com.cloudflare.api.account"],
    label: "mass_url_redirects_write",
    type: "edit",
    rowId: 1315,
    parsedName: "Bulk URL Redirects",
  },
  {
    id: "3518d0f75557482e952c6762d3e64903",
    name: "memberships",
    description: "Grants read access to a user's account memberships,",
    scopes: ["com.cloudflare.api.user"],
    label: "memberships_read",
    type: "read",
    rowId: 1316,
    parsedName: "Memberships",
  },
  {
    id: "9201bc6f42d440968aaab0c6f17ebb1d",
    name: "memberships",
    description: "Grants write access to a user's account memberships",
    scopes: ["com.cloudflare.api.user"],
    label: "memberships_write",
    type: "edit",
    rowId: 1317,
    parsedName: "Memberships",
  },
  {
    id: "ce18edbdcebf465e9d6d1d2fc80ffd42",
    name: "notifications",
    description: "Grants read access to notifications",
    scopes: ["com.cloudflare.api.account"],
    label: "notifications_read",
    type: "read",
    rowId: 1318,
    parsedName: "Notifications",
  },
  {
    id: "c3c847c5802d4ce3ba00e3e97b3c8555",
    name: "notifications",
    description: "Grants write access to Notifications",
    scopes: ["com.cloudflare.api.account"],
    label: "notifications_write",
    type: "edit",
    rowId: 1319,
    parsedName: "Notifications",
  },
  {
    id: "7b32a91ece3140d4b3c2c56f23fc8e35",
    name: "origin",
    description: "Grants read access to origin phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "origin_read",
    type: "read",
    rowId: 1320,
    parsedName: "Origin Rules",
  },
  {
    id: "a4308c6855c84eb2873e01b6cc85cbb3",
    name: "origin",
    description: "Grants write access to origin phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "origin_write",
    type: "edit",
    rowId: 1321,
    parsedName: "Origin Rules",
  },
  {
    id: "b415b70a4fd1412886f164451f20405c",
    name: "page_rules",
    description: "Grants read access to Page Rules",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "page_rules_read",
    type: "read",
    rowId: 1322,
    parsedName: "Page Rules",
  },
  {
    id: "ed07f6c337da4195b4e72a1fb2c6bcae",
    name: "page_rules",
    description: "Grants write access to Page Rules",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "page_rules_write",
    type: "edit",
    rowId: 1323,
    parsedName: "Page Rules",
  },
  {
    id: "440e6958bcc947329f8d56328d7322ce",
    name: "page",
    description: "Grants write access to Page Shield",
    scopes: ["com.cloudflare.api.account"],
    label: "page_shield",
    type: "shield",
    rowId: 1324,
    parsedName: "Cloudflare Pages",
  },
  {
    id: "050531528b044d58bbb71666fef7c07c",
    name: "page_shield",
    description: "Grants read access to Page Shield across the whole account",
    scopes: ["com.cloudflare.api.account"],
    label: "page_shield_read",
    type: "read",
    rowId: 1325,
    parsedName: "Page Shield",
  },
  {
    id: "87065285ab38463481e72815eefd18c3",
    name: "page_shield",
    description: "Grants write access to Page Shield",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "page_shield_write",
    type: "edit",
    rowId: 1326,
    parsedName: "Page Shield",
  },
  {
    id: "e247aedd66bd41cc9193af0213416666",
    name: "page",
    description: "Grants read access to Cloudflare Pages",
    scopes: ["com.cloudflare.api.account"],
    label: "page_read",
    type: "read",
    rowId: 1327,
    parsedName: "Cloudflare Pages",
  },
  {
    id: "8d28297797f24fb8a0c332fe0866ec89",
    name: "page",
    description: "Grants write access to Cloudflare Pages",
    scopes: ["com.cloudflare.api.account"],
    label: "page_write",
    type: "edit",
    rowId: 1328,
    parsedName: "Cloudflare Pages",
  },
  {
    id: "14b9cf2f410f4c0c9a16bb10a81c0e0b",
    name: "pipelines",
    description: "Grants read access to Cloudflare Pipelines",
    scopes: ["com.cloudflare.api.account"],
    label: "pipelines_read",
    type: "read",
    rowId: 1329,
    parsedName: "Workers Pipelines",
  },
  {
    id: "5606e7405dc542949d949d59993d321f",
    name: "pipelines",
    description: "Grants access to Send Events to Cloudflare Pipelines",
    scopes: ["com.cloudflare.api.account"],
    label: "pipelines_send",
    type: "send",
    rowId: 1330,
    parsedName: "Workers Pipelines",
  },
  {
    id: "e34111af393449539859485aa5ddd5bd",
    name: "pipelines",
    description: "Grants write access to Cloudflare Pipelines",
    scopes: ["com.cloudflare.api.account"],
    label: "pipelines_write",
    type: "edit",
    rowId: 1331,
    parsedName: "Workers Pipelines",
  },
  {
    id: "fd7f886c75a244389e892c4c3c068292",
    name: "pubsub",
    description: "Grants read access to Pubsub Configurations\n",
    scopes: ["com.cloudflare.api.account"],
    label: "pubsub_read",
    type: "read",
    rowId: 1332,
    parsedName: "Pub/Sub",
  },
  {
    id: "910b6ecca1c5411bb894e787362d1312",
    name: "pubsub",
    description: "Grants full access to Pubsub Configurations\n",
    scopes: ["com.cloudflare.api.account"],
    label: "pubsub_write",
    type: "edit",
    rowId: 1333,
    parsedName: "Pub/Sub",
  },
  {
    id: "84a7755d54c646ca87cd50682a34bf7c",
    name: "queues",
    description: "Grants read access to Cloudflare Queues",
    scopes: ["com.cloudflare.api.account"],
    label: "queues_read",
    type: "read",
    rowId: 1334,
    parsedName: "Queues",
  },
  {
    id: "366f57075ffc42689627bcf8242a1b6d",
    name: "queues",
    description: "Grants write access to Cloudflare Queues",
    scopes: ["com.cloudflare.api.account"],
    label: "queues_write",
    type: "edit",
    rowId: 1335,
    parsedName: "Queues",
  },
  {
    id: "dfe525ec7b07472c827d8d009178b2ac",
    name: "radar",
    description: "Grants access to reading Radar",
    scopes: ["com.cloudflare.api.account"],
    label: "radar_read",
    type: "read",
    rowId: 1336,
    parsedName: "Radar",
  },
  {
    id: "93ae59e7a40c4287a57ff6e501186a63",
    name: "response_compression",
    description: "Grants read access to the response compression phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "response_compression_read",
    type: "read",
    rowId: 1337,
    parsedName: "Response Compression",
  },
  {
    id: "4bd3fb513a23494aa1341a7e1eb6e080",
    name: "response_compression",
    description: "Grants write access to the response compression phase",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "response_compression_write",
    type: "edit",
    rowId: 1338,
    parsedName: "Response Compression",
  },
  {
    id: "58abbad6d2ce40abb2594fbe932a2e0e",
    name: "account_rule_policies",
    description: "Grants read access to Rule Policies",
    scopes: ["com.cloudflare.api.account"],
    label: "account_rule_policies_read",
    type: "read",
    rowId: 1339,
    parsedName: "Rule Policies",
  },
  {
    id: "61ddc58f1da14f95b33b41213360cbeb",
    name: "account_rule_policies",
    description: "Grants write access to Rule Policies",
    scopes: ["com.cloudflare.api.account"],
    label: "account_rule_policies_write",
    type: "edit",
    rowId: 1340,
    parsedName: "Rule Policies",
  },
  {
    id: "d5812c023a5048b4882175a28952362d",
    name: "scim_provisioning",
    description: "Grants membership permissions needed for SCIM provisioning",
    scopes: ["com.cloudflare.api.account"],
    label: "scim_provisioning_write",
    type: "edit",
    rowId: 1341,
    parsedName: "SCIM Provisioning",
  },
  {
    id: "7b7216b327b04b8fbc8f524e1f9b7531",
    name: "ssl_and_certificates",
    description: "Grants read access to SSL configuration and cert management",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "ssl_and_certificates_read",
    type: "read",
    rowId: 1342,
    parsedName: "SSL and Certificates",
  },
  {
    id: "c03055bc037c4ea9afb9a9f104b7b721",
    name: "ssl_and_certificates",
    description: "Grants write access to SSL configuration and cert management",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "ssl_and_certificates_write",
    type: "edit",
    rowId: 1343,
    parsedName: "SSL and Certificates",
  },
  {
    id: "853643ed57244ed1a05a7c024af9ab5a",
    name: "sanitize",
    description: "Grants read access to sanitization",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "sanitize_read",
    type: "read",
    rowId: 1344,
    parsedName: "Sanitize",
  },
  {
    id: "89bb8c37d46042e98b84560eaaa6379f",
    name: "sanitize",
    description: "Grants write access to sanitization",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "sanitize_write",
    type: "edit",
    rowId: 1345,
    parsedName: "Sanitize",
  },
  {
    id: "595409c54a24444b80a495620b2d614c",
    name: "select_configuration",
    description: "Grants read access to select configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "select_configuration_read",
    type: "read",
    rowId: 1346,
    parsedName: "Select Configuration",
  },
  {
    id: "235eac9bb64942b49cb805cc851cb000",
    name: "select_configuration",
    description: "Grants write access to select configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "select_configuration_write",
    type: "edit",
    rowId: 1347,
    parsedName: "Select Configuration",
  },
  {
    id: "74c654eb4aac40e28d6c6caa4c5aeb3d",
    name: "snippets",
    description: "Grants read access to Snippets",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "snippets_read",
    type: "read",
    rowId: 1348,
    parsedName: "Snippets",
  },
  {
    id: "dadeaf3abdf14126a77a35e0c92fc36e",
    name: "snippets",
    description: "Grants write access to Snippets",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "snippets_write",
    type: "edit",
    rowId: 1349,
    parsedName: "Snippets",
  },
  {
    id: "de21485a24744b76a004aa153898f7fe",
    name: "stream",
    description: "Grants read access to Cloudflare Stream",
    scopes: ["com.cloudflare.api.account"],
    label: "stream_read",
    type: "read",
    rowId: 1350,
    parsedName: "Stream",
  },
  {
    id: "714f9c13a5684c2885a793f5edb36f59",
    name: "stream",
    description: "Grants write access to Cloudflare Stream",
    scopes: ["com.cloudflare.api.account"],
    label: "stream_write",
    type: "edit",
    rowId: 1351,
    parsedName: "Stream",
  },
  {
    id: "3f376c8e6f764a938b848bd01c8995c4",
    name: "teams",
    description: "Grants read access to teams (Zero Trust)",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_read",
    type: "read",
    rowId: 1352,
    parsedName: "Zero Trust",
  },
  {
    id: "efb81b5cd37d49f3be1da9363a6d7a19",
    name: "teams",
    description: "Grants reporting access to teams (Zero Trust)",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_report",
    type: "report",
    rowId: 1353,
    parsedName: "Zero Trust",
  },
  {
    id: "b33f02c6f7284e05a6f20741c0bb0567",
    name: "teams",
    description: "Grants write access to teams (Zero Trust)",
    scopes: ["com.cloudflare.api.account"],
    label: "teams_write",
    type: "edit",
    rowId: 1354,
    parsedName: "Zero Trust",
  },
  {
    id: "a9a99455bf3245f6a5a244f909d74830",
    name: "transform_rules",
    description: "Grants read access to transform rules",
    scopes: ["com.cloudflare.api.account"],
    label: "transform_rules_read",
    type: "read",
    rowId: 1355,
    parsedName: "Transform Rules",
  },
  {
    id: "ae16e88bc7814753a1894c7ce187ab72",
    name: "transform_rules",
    description: "Grants write access to transform rules",
    scopes: ["com.cloudflare.api.account"],
    label: "transform_rules_write",
    type: "edit",
    rowId: 1356,
    parsedName: "Transform Rules",
  },
  {
    id: "f0ba3733e746429182fcd40ec648c066",
    name: "trust_and_safety",
    description: "Grants access to read abuse reports and abuse actions",
    scopes: ["com.cloudflare.api.account"],
    label: "trust_and_safety_read",
    type: "read",
    rowId: 1357,
    parsedName: "Trust and Safety",
  },
  {
    id: "120f843a9c074f399b830e542e5616b8",
    name: "trust_and_safety",
    description:
      "Grants access to interact with abuse reports and abuse actions",
    scopes: ["com.cloudflare.api.account"],
    label: "trust_and_safety_write",
    type: "edit",
    rowId: 1358,
    parsedName: "Trust and Safety",
  },
  {
    id: "5d78fd7895974fd0bdbbbb079482721b",
    name: "challenge_widgets",
    description: "Grants read access to Turnstile",
    scopes: ["com.cloudflare.api.account"],
    label: "challenge_widgets_read",
    type: "read",
    rowId: 1359,
    parsedName: "Turnstile",
  },
  {
    id: "755c05aa014b4f9ab263aa80b8167bd8",
    name: "challenge_widgets",
    description: "Grants write access to Turnstile",
    scopes: ["com.cloudflare.api.account"],
    label: "challenge_widgets_write",
    type: "edit",
    rowId: 1360,
    parsedName: "Turnstile",
  },
  {
    id: "5d613a610b294788a29572aaac2f254d",
    name: "url_scanner",
    description: "Grants read access to URL Scanner API",
    scopes: ["com.cloudflare.api.account"],
    label: "url_scanner_read",
    type: "read",
    rowId: 1361,
    parsedName: "URL Scanner",
  },
  {
    id: "2a400bcb29154daab509fe07e3facab0",
    name: "url_scanner",
    description: "Grants write access to URL Scanner API",
    scopes: ["com.cloudflare.api.account"],
    label: "url_scanner_write",
    type: "edit",
    rowId: 1362,
    parsedName: "URL Scanner",
  },
  {
    id: "8acbe5bb0d54464ab867149d7f7cf8ac",
    name: "user_details",
    description: "Grants read access to user details",
    scopes: ["com.cloudflare.api.user"],
    label: "user_details_read",
    type: "read",
    rowId: 1363,
    parsedName: "User Details",
  },
  {
    id: "55a5e17cc99e4a3fa1f3432d262f2e55",
    name: "user_details",
    description: "Grants write access to user details",
    scopes: ["com.cloudflare.api.user"],
    label: "user_details_write",
    type: "edit",
    rowId: 1364,
    parsedName: "User Details",
  },
  {
    id: "1799edaae5db489294430e20d9b519e0",
    name: "vectorize",
    description: "Grants read access to Vectorize configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "vectorize_read",
    type: "read",
    rowId: 1365,
    parsedName: "Vectorize",
  },
  {
    id: "64156ba5be47441096c83c7fc17c488b",
    name: "vectorize",
    description: "Grants write access to Vectorize configuration",
    scopes: ["com.cloudflare.api.account"],
    label: "vectorize_write",
    type: "edit",
    rowId: 1366,
    parsedName: "Vectorize",
  },
  {
    id: "cab5202d07ef47beae788e6bc95cb6fe",
    name: "waiting_rooms",
    description: "Grants read access to Waiting Rooms\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "waiting_rooms_read",
    type: "read",
    rowId: 1367,
    parsedName: "Waiting Room",
  },
  {
    id: "24fc124dc8254e0db468e60bf410c800",
    name: "waiting_rooms",
    description: "Grants write access to Waiting Rooms\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "waiting_rooms_write",
    type: "edit",
    rowId: 1368,
    parsedName: "Waiting Room",
  },
  {
    id: "8e31f574901c42e8ad89140b28d42112",
    name: "web3_hostnames",
    description: "Grants read access to Web3 Hostnames\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "web3_hostnames_read",
    type: "read",
    rowId: 1369,
    parsedName: "Web3 Hostnames",
  },
  {
    id: "5ea6da42edb34811a78d1b007557c0ca",
    name: "web3_hostnames",
    description: "Grants write access to Web3 Hostnames\n",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "web3_hostnames_write",
    type: "edit",
    rowId: 1370,
    parsedName: "Web3 Hostnames",
  },
  {
    id: "a92d2450e05d4e7bb7d0a64968f83d11",
    name: "ai",
    description: "Grants access to invoke Workers AI models",
    scopes: ["com.cloudflare.api.account"],
    label: "ai_read",
    type: "read",
    rowId: 1371,
    parsedName: "Workers AI",
  },
  {
    id: "bacc64e0f6c34fc0883a1223f938a104",
    name: "ai",
    description: "Grants access to invoke Workers AI models and edit assets",
    scopes: ["com.cloudflare.api.account"],
    label: "ai_write",
    type: "edit",
    rowId: 1372,
    parsedName: "Workers AI",
  },
  {
    id: "ad99c5ae555e45c4bef5bdf2678388ba",
    name: "workers_ci",
    description: "Grants read access to Workers CI",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_ci_read",
    type: "read",
    rowId: 1373,
    parsedName: "Workers CI",
  },
  {
    id: "2e095cf436e2455fa62c9a9c2e18c478",
    name: "workers_ci",
    description: "Grants write access to Workers CI",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_ci_write",
    type: "edit",
    rowId: 1374,
    parsedName: "Workers CI",
  },
  {
    id: "8b47d2786a534c08a1f94ee8f9f599ef",
    name: "workers_kv_storage",
    description: "Grants read access to Cloudflare Workers KV Storage",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_kv_storage_read",
    type: "read",
    rowId: 1375,
    parsedName: "Workers KV Storage",
  },
  {
    id: "f7f0eda5697f475c90846e879bab8666",
    name: "workers_kv_storage",
    description: "Grants write access to Cloudflare Workers KV Storage",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_kv_storage_write",
    type: "edit",
    rowId: 1376,
    parsedName: "Workers KV Storage",
  },
  {
    id: "6a018a9f2fc74eb6b293b0c548f38b39",
    name: "workers_r2_bucket_item",
    description: "Grants read access to Cloudflare R2 Bucket Scoped Storage",
    scopes: ["com.cloudflare.edge.r2.bucket"],
    label: "workers_r2_bucket_item_read",
    type: "read",
    rowId: 1377,
    parsedName: "Workers R2 Bucket Scoped Storage",
  },
  {
    id: "2efd5506f9c8494dacb1fa10a3e7d5b6",
    name: "workers_r2_bucket_item",
    description: "Grants write access to Cloudflare R2 Bucket Scoped Storage",
    scopes: ["com.cloudflare.edge.r2.bucket"],
    label: "workers_r2_bucket_item_write",
    type: "edit",
    rowId: 1378,
    parsedName: "Workers R2 Bucket Scoped Storage",
  },
  {
    id: "b4992e1108244f5d8bfbd5744320c2e1",
    name: "workers_r2",
    description: "Grants read access to Cloudflare R2 Storage",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_r2_read",
    type: "read",
    rowId: 1379,
    parsedName: "Workers R2 Storage",
  },
  {
    id: "bf7481a1826f439697cb59a20b22293e",
    name: "workers_r2",
    description: "Grants write access to Cloudflare R2 Storage",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_r2_write",
    type: "edit",
    rowId: 1380,
    parsedName: "Workers R2 Storage",
  },
  {
    id: "2072033d694d415a936eaeb94e6405b8",
    name: "workers_routes",
    description:
      "Grants read access to Cloudflare Workers and Workers KV Storage",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "workers_routes_read",
    type: "read",
    rowId: 1381,
    parsedName: "Workers Routes",
  },
  {
    id: "28f4b596e7d643029c524985477ae49a",
    name: "workers_routes",
    description:
      "Grants write access to Cloudflare Workers and Workers KV Storage",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "workers_routes_write",
    type: "edit",
    rowId: 1382,
    parsedName: "Workers Routes",
  },
  {
    id: "1a71c399035b4950a1bd1466bbe4f420",
    name: "workers_scripts",
    description: "Grants read access to Cloudflare Workers scripts",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_scripts_read",
    type: "read",
    rowId: 1383,
    parsedName: "Workers Scripts",
  },
  {
    id: "e086da7e2179491d91ee5f35b3ca210a",
    name: "workers_scripts",
    description: "Grants write access to Cloudflare Workers scripts",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_scripts_write",
    type: "edit",
    rowId: 1384,
    parsedName: "Workers Scripts",
  },
  {
    id: "05880cd1bdc24d8bae0be2136972816b",
    name: "workers_tail",
    description: "Grants `wrangler tail` read permissions",
    scopes: ["com.cloudflare.api.account"],
    label: "workers_tail_read",
    type: "read",
    rowId: 1385,
    parsedName: "Workers Tail",
  },
  {
    id: "cdeb15b336e640a2965df8c65052f1e0",
    name: "zaraz",
    description: "Can edit and publish Zaraz settings.",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zaraz_write",
    type: "edit_publish",
    rowId: 1386,
    parsedName: "Zaraz",
  },
  {
    id: "89d5bf002389496e9994b8c30608b5d0",
    name: "zaraz",
    description: "Can edit Zaraz settings.",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zaraz_edit",
    type: "edit",
    rowId: 1387,
    parsedName: "Zaraz",
  },
  {
    id: "5bdbde7e76144204a244274eac3eb0eb",
    name: "zaraz",
    description: "Grants read access to Zaraz settings.",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zaraz_read",
    type: "read",
    rowId: 1388,
    parsedName: "Zaraz",
  },
  {
    id: "a1a6298e52584c8fb6313760a30c681e",
    name: "access_seats",
    description: "Grants write access to Cloudflare Access and Gateway seats",
    scopes: ["com.cloudflare.api.account"],
    label: "access_seats_write",
    type: "edit",
    rowId: 1389,
    parsedName: "Zero Trust: Seats",
  },
  {
    id: "0a6cfe8cd3ed445e918579e2fb13087b",
    name: "zone_dns_settings",
    description: "Grants read access to Zone DNS Settings",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_dns_settings_read",
    type: "read",
    rowId: 1390,
    parsedName: "Zone DNS Settings",
  },
  {
    id: "c4df38be41c247b3b4b7702e76eadae0",
    name: "zone_dns_settings",
    description: "Grants write access to Zone DNS Settings",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_dns_settings_write",
    type: "edit",
    rowId: 1391,
    parsedName: "Zone DNS Settings",
  },
  {
    id: "c8fed203ed3043cba015a93ad1616f1f",
    name: "zone",
    description: "Grants read access to zone management",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_read",
    type: "read",
    rowId: 1392,
    parsedName: "Zone",
  },
  {
    id: "517b21aee92c4d89936c976ba6e4be55",
    name: "zone_settings",
    description: "Grants read access to zone settings",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_settings_read",
    type: "read",
    rowId: 1393,
    parsedName: "Zone Settings",
  },
  {
    id: "3030687196b94b638145a3953da2b699",
    name: "zone_settings",
    description: "Grants write access to zone settings",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_settings_write",
    type: "edit",
    rowId: 1394,
    parsedName: "Zone Settings",
  },
  {
    id: "211a4c0feb3e43b3a2d41f1443a433e7",
    name: "zone_transform_rules",
    description: "Grants read access to transform rules at zone level",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_transform_rules_read",
    type: "read",
    rowId: 1395,
    parsedName: "Transform Rules",
  },
  {
    id: "0ac90a90249747bca6b047d97f0803e9",
    name: "zone_transform_rules",
    description: "Grants write access to transform rules at zone level",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_transform_rules_write",
    type: "edit",
    rowId: 1396,
    parsedName: "Transform Rules",
  },
  {
    id: "1b1ea24cf0904d33903f0cc7e54e280f",
    name: "zone_versioning",
    description: "Grants read-only access to Zone Versioning",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_versioning_read",
    type: "read",
    rowId: 1397,
    parsedName: "Zone Versioning",
  },
  {
    id: "c9915d86fbff46af9dd945c0a882294b",
    name: "zone_versioning",
    description: "Grants full access to Zone Versioning",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_versioning_write",
    type: "edit",
    rowId: 1398,
    parsedName: "Zone Versioning",
  },
  {
    id: "dbc512b354774852af2b5a5f4ba3d470",
    name: "zone_waf",
    description: "Grants read access to Zone WAF",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_waf_read",
    type: "read",
    rowId: 1399,
    parsedName: "Zone WAF",
  },
  {
    id: "fb6778dc191143babbfaa57993f1d275",
    name: "zone_waf",
    description: "Grants write access to Zone WAF",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_waf_write",
    type: "edit",
    rowId: 1400,
    parsedName: "Zone WAF",
  },
  {
    id: "e6d2666161e84845a636613608cee8d5",
    name: "zone",
    description: "Grants write access to zone management",
    scopes: ["com.cloudflare.api.account.zone"],
    label: "zone_write",
    type: "edit",
    rowId: 1401,
    parsedName: "Zone",
  },
];
